In [3]:
import numpy as np
from sklearn.utils.multiclass import type_of_target

y = np.array(['apple', 'pear', 'apple', 'orange'])
print(y)

print(type_of_target(y))


['apple' 'pear' 'apple' 'orange']
multiclass


In [2]:
import numpy as np
from sklearn.preprocessing import LabelBinarizer
y = np.array(['apple', 'pear', 'apple', 'orange'])
y_dense = LabelBinarizer().fit_transform(y)
print(y_dense)


from scipy import sparse
y_sparse = sparse.csr_matrix(y_dense)
print(y_sparse)

[[1 0 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]]
  (0, 0)	1
  (1, 2)	1
  (2, 0)	1
  (3, 1)	1


In [1]:
from sklearn import datasets
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC
X, y = datasets.load_iris(return_X_y=True)
OneVsRestClassifier(LinearSVC(random_state=0)).fit(X, y).predict(X)

C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [2]:
# logistic regression for multi-class classification using built-in one-vs-rest
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)
# define model
model = LogisticRegression(multi_class='ovr')
# fit model
model.fit(X, y)
# make predictions
yhat = model.predict(X)
print(yhat)

[1 0 1 2 0 2 1 2 0 1 1 0 2 1 0 1 2 0 1 0 0 1 0 2 0 0 2 0 1 1 2 1 0 2 0 0 0
 1 1 2 2 1 0 1 0 2 0 0 0 2 0 1 2 0 2 2 1 2 1 0 2 2 2 1 0 1 1 1 0 2 0 2 2 1
 0 0 0 0 0 1 2 0 2 0 2 2 2 1 0 1 2 1 1 1 0 2 0 2 1 1 0 1 1 0 0 0 2 2 2 2 1
 0 0 1 2 0 0 0 0 2 2 2 1 0 1 2 2 0 1 0 2 1 0 0 2 0 0 0 0 1 1 1 0 0 1 1 2 0
 0 1 1 1 2 1 0 0 2 2 1 0 2 1 2 2 1 0 2 0 2 1 0 0 0 0 0 1 2 0 2 1 0 1 0 0 1
 0 0 0 1 0 1 2 1 0 0 1 1 0 2 1 1 0 1 1 0 0 0 1 2 2 0 2 0 1 0 2 2 0 0 2 2 1
 2 2 1 0 1 1 2 1 1 1 1 2 1 1 1 1 2 0 2 2 2 2 0 0 0 1 2 2 2 0 2 2 2 2 1 2 0
 1 1 0 1 2 1 2 0 2 0 0 0 2 1 1 0 0 1 1 2 0 1 1 1 1 2 0 0 0 1 2 0 0 1 0 0 2
 0 0 2 1 2 0 2 2 0 2 0 2 1 1 2 2 1 2 0 1 2 2 2 0 0 0 1 2 1 0 2 1 0 1 2 0 0
 1 1 2 0 1 0 0 1 2 1 1 2 2 0 2 1 1 0 1 0 0 0 0 0 0 1 2 2 0 0 0 1 0 0 1 2 1
 0 2 1 0 1 0 1 1 1 0 1 0 2 0 1 1 0 1 1 1 1 0 0 0 1 2 2 2 0 0 0 1 1 1 1 0 2
 2 0 1 2 1 0 2 0 0 1 1 0 2 2 0 2 2 0 1 0 0 0 0 1 0 0 2 1 0 0 2 1 0 0 2 1 1
 2 0 0 2 0 1 0 0 0 2 0 0 0 1 0 1 0 1 0 0 0 1 0 0 1 2 1 2 0 0 2 1 2 0 0 1 2
 2 1 2 1 1 1 0 2 2 1 1 2 

In [4]:
# logistic regression for multi-class classification using a one-vs-rest
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)
# define model
model = LogisticRegression()
# define the ovr strategy
ovr = OneVsRestClassifier(model)
# fit model
ovr.fit(X, y)
# make predictions
yhat = ovr.predict(X)
print(yhat)

[1 0 1 2 0 2 1 2 0 1 1 0 2 1 0 1 2 0 1 0 0 1 0 2 0 0 2 0 1 1 2 1 0 2 0 0 0
 1 1 2 2 1 0 1 0 2 0 0 0 2 0 1 2 0 2 2 1 2 1 0 2 2 2 1 0 1 1 1 0 2 0 2 2 1
 0 0 0 0 0 1 2 0 2 0 2 2 2 1 0 1 2 1 1 1 0 2 0 2 1 1 0 1 1 0 0 0 2 2 2 2 1
 0 0 1 2 0 0 0 0 2 2 2 1 0 1 2 2 0 1 0 2 1 0 0 2 0 0 0 0 1 1 1 0 0 1 1 2 0
 0 1 1 1 2 1 0 0 2 2 1 0 2 1 2 2 1 0 2 0 2 1 0 0 0 0 0 1 2 0 2 1 0 1 0 0 1
 0 0 0 1 0 1 2 1 0 0 1 1 0 2 1 1 0 1 1 0 0 0 1 2 2 0 2 0 1 0 2 2 0 0 2 2 1
 2 2 1 0 1 1 2 1 1 1 1 2 1 1 1 1 2 0 2 2 2 2 0 0 0 1 2 2 2 0 2 2 2 2 1 2 0
 1 1 0 1 2 1 2 0 2 0 0 0 2 1 1 0 0 1 1 2 0 1 1 1 1 2 0 0 0 1 2 0 0 1 0 0 2
 0 0 2 1 2 0 2 2 0 2 0 2 1 1 2 2 1 2 0 1 2 2 2 0 0 0 1 2 1 0 2 1 0 1 2 0 0
 1 1 2 0 1 0 0 1 2 1 1 2 2 0 2 1 1 0 1 0 0 0 0 0 0 1 2 2 0 0 0 1 0 0 1 2 1
 0 2 1 0 1 0 1 1 1 0 1 0 2 0 1 1 0 1 1 1 1 0 0 0 1 2 2 2 0 0 0 1 1 1 1 0 2
 2 0 1 2 1 0 2 0 0 1 1 0 2 2 0 2 2 0 1 0 0 0 0 1 0 0 2 1 0 0 2 1 0 0 2 1 1
 2 0 0 2 0 1 0 0 0 2 0 0 0 1 0 1 0 1 0 0 0 1 0 0 1 2 1 2 0 0 2 1 2 0 0 1 2
 2 1 2 1 1 1 0 2 2 1 1 2 

In [6]:
# SVM for multi-class classification using built-in one-vs-one
from sklearn.datasets import make_classification
from sklearn.svm import SVC
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)
# define model
model = SVC(decision_function_shape='ovo')
# fit model
model.fit(X, y)
# make predictions
yhat = model.predict(X)
print(yhat)

[1 0 1 2 0 2 2 2 0 0 1 0 2 2 0 1 2 0 1 0 0 0 0 2 0 0 2 0 1 1 2 1 0 2 0 0 0
 1 2 2 2 1 0 0 1 1 0 0 1 1 0 1 2 1 1 2 2 2 1 0 2 2 2 1 0 1 1 0 0 0 2 1 1 0
 0 0 2 0 2 1 2 0 0 0 1 2 2 2 0 1 2 2 1 0 0 1 1 2 0 1 0 0 1 1 1 0 2 2 2 2 1
 2 0 2 2 0 0 0 0 1 2 2 1 2 2 2 2 0 1 0 2 1 0 0 2 2 0 0 0 1 1 0 0 2 0 1 2 0
 2 1 2 0 0 1 0 0 2 2 1 2 2 1 2 0 1 2 2 0 2 1 0 0 2 0 0 0 2 0 2 1 0 0 0 0 0
 0 0 0 1 0 1 2 1 0 0 1 1 0 0 1 1 1 2 1 0 0 2 1 2 2 1 2 0 0 0 2 2 2 0 2 2 1
 1 2 1 1 1 1 2 1 0 1 1 2 1 1 1 1 2 0 2 2 1 1 2 0 0 0 1 1 2 2 2 2 1 2 1 1 0
 1 1 1 1 2 1 2 0 2 0 0 0 2 1 1 0 0 1 2 2 0 1 0 0 1 1 1 1 2 1 2 0 2 1 0 0 1
 0 0 2 1 1 0 2 2 0 0 0 2 1 0 2 2 1 1 0 1 0 2 2 0 0 0 1 2 1 1 1 2 0 1 2 1 0
 1 1 2 0 1 0 0 1 2 0 1 2 2 2 2 0 1 0 1 0 0 2 0 0 0 1 2 1 0 0 0 1 0 0 1 0 1
 0 2 0 0 1 0 1 1 1 0 0 2 2 2 1 2 0 1 1 1 1 0 0 0 1 2 2 1 0 2 0 1 0 1 1 0 1
 2 0 0 2 1 0 2 0 0 1 2 0 2 2 0 2 2 2 0 0 2 2 2 1 0 0 1 1 0 2 2 1 0 0 2 2 1
 2 0 0 1 0 0 0 0 0 2 1 0 0 1 2 1 1 0 0 0 0 1 0 0 1 2 1 0 0 0 1 1 2 2 0 1 2
 2 0 2 2 0 1 0 2 2 1 1 2 

In [7]:
# SVM for multi-class classification using one-vs-one
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.multiclass import OneVsOneClassifier
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)
# define model
model = SVC()
# define ovo strategy
ovo = OneVsOneClassifier(model)
# fit model
ovo.fit(X, y)
# make predictions
yhat = ovo.predict(X)
print(yhat)

[1 0 1 2 0 2 2 2 0 0 1 0 2 2 0 1 2 0 1 0 0 0 0 2 0 0 2 0 1 1 2 1 0 2 0 0 0
 1 2 2 2 1 0 0 1 1 0 0 1 1 0 1 2 1 1 2 2 2 1 0 2 2 2 1 0 1 1 0 0 0 2 1 1 0
 0 0 2 0 2 1 2 0 0 0 1 2 2 2 0 1 2 2 1 0 0 1 1 2 0 1 0 0 1 1 1 0 2 2 2 2 1
 2 0 2 2 0 0 0 0 1 2 2 1 2 2 2 2 0 1 0 2 1 0 0 2 2 0 0 0 1 1 0 0 2 0 1 2 0
 2 1 2 0 0 1 0 0 2 2 1 2 2 1 2 0 1 2 2 0 2 1 0 0 2 0 0 0 2 0 2 1 0 0 0 0 0
 0 0 0 1 0 1 2 1 0 0 1 1 0 0 1 1 1 2 1 0 0 2 1 2 2 1 2 0 0 0 2 2 2 0 2 2 1
 1 2 1 1 1 1 2 1 0 1 1 2 1 1 1 1 2 0 2 2 1 1 2 0 0 0 1 1 2 2 2 2 1 2 1 1 0
 1 1 1 1 2 1 2 0 2 0 0 0 2 1 1 0 0 1 2 2 0 1 0 0 1 1 1 1 2 1 2 0 2 1 0 0 1
 0 0 2 1 1 0 2 2 0 1 0 2 1 0 2 2 1 1 0 1 0 2 2 0 0 0 1 2 1 1 1 2 0 1 2 1 0
 1 1 2 0 1 0 0 1 2 0 1 2 2 2 2 0 1 0 1 0 0 2 0 0 0 1 2 1 0 0 0 1 0 0 1 0 1
 0 2 0 0 1 0 1 1 1 0 0 2 2 2 1 2 0 1 1 1 1 0 0 0 1 2 2 1 0 2 0 1 0 1 1 0 1
 2 0 0 2 1 0 2 0 0 1 2 0 2 2 0 2 2 2 0 0 2 2 2 1 0 0 1 1 0 2 2 1 0 0 2 2 1
 2 2 0 1 0 0 0 0 0 2 1 0 0 1 2 1 1 0 0 0 0 1 0 0 1 2 1 1 0 0 1 1 2 2 0 1 2
 2 0 2 2 0 1 0 2 2 1 1 2 

In [8]:
from sklearn import datasets
from sklearn.multiclass import OneVsOneClassifier
from sklearn.svm import LinearSVC
X, y = datasets.load_iris(return_X_y=True)
OneVsOneClassifier(LinearSVC(random_state=0)).fit(X, y).predict(X)

C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
from sklearn import datasets
from sklearn.multiclass import OutputCodeClassifier
from sklearn.svm import LinearSVC
X, y = datasets.load_iris(return_X_y=True)
clf = OutputCodeClassifier(LinearSVC(random_state=0),
                           code_size=2, random_state=0)
clf.fit(X, y).predict(X)

C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
# multi-class classification dataset
from collections import Counter
from sklearn.datasets import make_classification
# define dataset
X, y = make_classification(n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=1, n_classes=3)
# summarize the dataset
print(X.shape, y.shape)
# summarize the number of classes
print(Counter(y))

(1000, 20) (1000,)
Counter({2: 335, 1: 333, 0: 332})


In [11]:
# evaluate error-correcting output codes for multi-class classification
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OutputCodeClassifier
# define dataset
X, y = make_classification(n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=1, n_classes=3)
# define the binary classification model
model = LogisticRegression()
# define the ecoc model
ecoc = OutputCodeClassifier(model, code_size=2, random_state=1)
# define the evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate the model and collect the scores
n_scores = cross_val_score(ecoc, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
# summarize the performance
print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Accuracy: 0.766 (0.037)


In [12]:
# use error-correcting output codes model as a final model and make a prediction
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OutputCodeClassifier
# define dataset
X, y = make_classification(n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=1, n_classes=3)
# define the binary classification model
model = LogisticRegression()
# define the ecoc model
ecoc = OutputCodeClassifier(model, code_size=2, random_state=1)
# fit the model on the whole dataset
ecoc.fit(X, y)
# make a single prediction
row = [[0.04339387, 2.75542632, -3.79522705, -0.71310994, -3.08888853, -1.2963487, -1.92065166, -3.15609907, 1.37532356, 3.61293237, 1.00353523, -3.77126962, 2.26638828, -10.22368666, -0.35137382, 1.84443763, 3.7040748, 2.50964286, 2.18839505, -2.31211692]]
yhat = ecoc.predict(row)
print('Predicted Class: %d' % yhat[0])

Predicted Class: 0


In [13]:
from sklearn import datasets
from sklearn.multiclass import OutputCodeClassifier
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

# 数据获取
iris = datasets.load_iris()
X, y = iris.data, iris.target
print("样本数量:%d, 特征数量:%d" % X.shape)

# 模型对象创建
# code_size: 指定最终使用多少个子模型，实际的子模型的数量=int(code_size*label_number)
# code_size设置为1，等价于ovr子模型个数；
# 设置为0~1, 那相当于使用比较少的数据划分，效果比ovr差; 
# 设置为大于1的值，那么相当于存在部分模型冗余的情况
clf = OutputCodeClassifier(LinearSVC(random_state=0), code_size=30, random_state=0)
# 模型构建
clf.fit(X, y)

# 输出预测结果值
print(clf.predict(X))
print("准确率:%.3f" % accuracy_score(y, clf.predict(X)))

# 模型属性输出
k = 1
for item in clf.estimators_:
    print("第%d个模型:" % k, end="")
    print(item)
    k += 1
print(clf.classes_)

样本数量:150, 特征数量:4


C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: Convergence

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1
 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
准确率:0.967
第1个模型:LinearSVC(random_state=0)
第2个模型:_ConstantPredictor()
第3个模型:LinearSVC(random_state=0)
第4个模型:LinearSVC(random_state=0)
第5个模型:LinearSVC(random_state=0)
第6个模型:LinearSVC(random_state=0)
第7个模型:LinearSVC(random_state=0)
第8个模型:LinearSVC(random_state=0)
第9个模型:_ConstantPredictor()
第10个模型:_ConstantPredictor()
第11个模型:LinearSVC(random_state=0)
第12个模型:LinearSVC(random_state=0)
第13个模型:LinearSVC(random_state=0)
第14个模型:_ConstantPredictor()
第15个模型:LinearSVC(random_state=0)
第16个模型:LinearSVC(random_state=0)
第17个模型:LinearSVC(random_state=0)
第18个模型:LinearSVC(random_state=0)
第19个模型:LinearSVC(random_state=0)
第20个模型:LinearSVC(random_state=0)
第21个模型:LinearSVC(random_state=0)
第22个模型:_ConstantPred

In [14]:
import numpy as np
from sklearn.datasets import make_multilabel_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.neighbors import KNeighborsClassifier

In [16]:
X, y = make_multilabel_classification(n_classes=3, random_state=0)
print(X)
print(y)
clf = MultiOutputClassifier(KNeighborsClassifier()).fit(X, y)
clf.predict(X[-2:])

[[3. 6. 1. ... 1. 5. 0.]
 [3. 5. 5. ... 1. 1. 1.]
 [3. 3. 5. ... 0. 2. 1.]
 ...
 [3. 7. 3. ... 2. 4. 2.]
 [7. 2. 1. ... 1. 1. 1.]
 [3. 5. 3. ... 1. 2. 4.]]
[[0 1 0]
 [0 1 0]
 [1 1 1]
 [1 1 1]
 [0 1 0]
 [1 1 0]
 [0 0 0]
 [1 0 0]
 [0 0 1]
 [0 0 0]
 [0 1 0]
 [0 0 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]
 [0 0 0]
 [0 1 0]
 [0 0 0]
 [1 1 1]
 [0 1 1]
 [0 0 1]
 [1 0 1]
 [0 1 0]
 [0 1 0]
 [1 1 0]
 [0 1 1]
 [0 0 1]
 [1 1 1]
 [1 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 0 0]
 [0 1 0]
 [0 1 0]
 [1 1 1]
 [1 1 1]
 [0 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 1]
 [1 1 0]
 [1 1 0]
 [1 1 1]
 [1 1 1]
 [0 0 1]
 [0 1 1]
 [1 1 1]
 [0 1 0]
 [1 1 1]
 [1 1 1]
 [0 1 0]
 [1 0 0]
 [0 1 1]
 [1 1 0]
 [0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 1]
 [0 1 1]
 [0 0 1]
 [1 1 0]
 [1 1 1]
 [1 0 1]
 [0 1 0]
 [0 1 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [0 0 1]
 [1 0 1]
 [1 1 0]
 [1 1 0]
 [1 1 1]
 [1 1 1]
 [1 0 1]
 [1 0 0]
 [1 1 1]
 [1 1 0]
 [1 1 1]
 [0 1 0]
 [1 0 0]
 [0 1 1]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 1 0]
 [0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 0

array([[1, 1, 0],
       [1, 1, 1]])

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report
from sklearn.datasets import make_multilabel_classification
from sklearn.svm import SVC
from sklearn.multioutput import MultiOutputClassifier

x, y = make_multilabel_classification(n_samples=5000, n_features=10,
                                      n_classes=2, random_state=0)

for i in range(10): 
 print(x[i]," => ", y[i])

xtrain, xtest, ytrain, ytest=train_test_split(x, y, train_size=0.95, random_state=0)
print(len(xtest))

svc = SVC(gamma="scale")
model = MultiOutputClassifier(estimator=svc)
print(model)

model.fit(xtrain, ytrain)
print(model.score(xtrain, ytrain))

yhat = model.predict(xtest)
auc_y1 = roc_auc_score(ytest[:,0],yhat[:,0])
auc_y2 = roc_auc_score(ytest[:,1],yhat[:,1])
 

print("ROC AUC y1: %.4f, y2: %.4f" % (auc_y1, auc_y2))

cm_y1 = confusion_matrix(ytest[:,0],yhat[:,0])
cm_y2 = confusion_matrix(ytest[:,1],yhat[:,1])
 

print(cm_y1)
print(cm_y2)

cr_y1 = classification_report(ytest[:,0],yhat[:,0])
cr_y2 = classification_report(ytest[:,1],yhat[:,1])

print(cr_y1)
print(cr_y2)

[ 5. 11.  8.  7.  7.  9.  0.  8.  5.  5.]  =>  [1 1]
[1. 2. 6. 1. 6. 8. 1. 9. 3. 8.]  =>  [0 1]
[8. 3. 7. 6. 4. 7. 0. 4. 7. 6.]  =>  [1 1]
[3. 4. 9. 4. 3. 7. 0. 2. 7. 8.]  =>  [1 1]
[ 8.  7. 10.  8.  7.  4.  1.  4. 10.  9.]  =>  [1 1]
[ 6.  5. 10.  5.  5.  3.  7.  6.  1.  9.]  =>  [0 0]
[ 7.  4. 13.  6.  5.  4.  1.  4.  5. 10.]  =>  [1 1]
[ 5.  2.  3. 14. 10.  4.  2.  0.  6. 12.]  =>  [1 0]
[10.  3.  1.  5.  7.  9.  3.  3.  4.  3.]  =>  [0 0]
[ 5.  4.  9.  5.  8. 10.  0.  8.  3.  9.]  =>  [0 1]
250
MultiOutputClassifier(estimator=SVC())
0.8688421052631579
ROC AUC y1: 0.9206, y2: 0.9202
[[ 80   8]
 [ 11 151]]
[[ 77   9]
 [  9 155]]
              precision    recall  f1-score   support

           0       0.88      0.91      0.89        88
           1       0.95      0.93      0.94       162

    accuracy                           0.92       250
   macro avg       0.91      0.92      0.92       250
weighted avg       0.92      0.92      0.92       250

              precision    recall 

In [2]:
import numpy as np
from sklearn.datasets import make_multilabel_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.neighbors import KNeighborsClassifier
X, y = make_multilabel_classification(n_classes=3, random_state=0)
clf = MultiOutputClassifier(KNeighborsClassifier()).fit(X, y)
clf.predict(X[-2:])

array([[1, 1, 0],
       [1, 1, 1]])

In [3]:
y = np.array([[1, 0, 0, 1], [0, 0, 1, 1], [0, 0, 0, 0]])
print(y)

[[1 0 0 1]
 [0 0 1 1]
 [0 0 0 0]]


In [7]:
from sklearn.datasets import make_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils import shuffle
import numpy as np
X, y1 = make_classification(n_samples=10, n_features=100, n_informative=30, n_classes=3, random_state=1)
print(X, y1)
y2 = shuffle(y1, random_state=1)
y3 = shuffle(y1, random_state=2)
print(y2)
print(y3)
Y = np.vstack((y1, y2, y3)).T
print(Y)

n_samples, n_features = X.shape # 10,100
n_outputs = Y.shape[1] # 3
n_classes = 3

forest = RandomForestClassifier(random_state=1)

multi_target_forest = MultiOutputClassifier(forest, n_jobs=-1)


multi_target_forest.fit(X, Y).predict(X)

[[-9.34327201e-01  1.56624579e+00 -1.00725887e+00 -3.08376593e+00
  -4.21430086e+00  1.16986584e-01  4.17638636e-01  9.00653742e-01
   3.93005059e+00 -6.50885358e-01  1.29279861e-01  1.63423085e+00
   4.91320357e-01  1.14596589e+00  9.21903246e-01 -2.31502687e+00
  -4.84047630e-01 -4.55542563e-01  7.34029572e-01  1.50469875e+00
   5.82357527e-01  1.02239602e+00  2.12138407e+00 -1.16327945e+00
   2.33826928e+00  6.34323770e-01 -4.01455641e+00  6.01882630e-01
  -6.59967952e-01  1.04178795e+00 -1.28307651e+01  1.92709640e+00
   1.24955216e+00  1.29391297e+00 -1.85151553e-01 -9.00264870e-02
  -4.78124907e-01  1.65233362e+00  4.37764479e-01  1.67131175e+00
  -2.20026617e-02  2.35819835e-02  2.32405079e-01 -6.08059465e-01
   6.24715074e-01  5.96586474e-01 -4.72840351e+00 -1.04025224e+00
   8.05591079e-01 -7.20947438e-01 -6.21240217e-01  3.80783793e+00
   6.31396194e+00 -9.44578343e-01 -9.87882061e-01  3.21386465e-01
  -7.73969875e-01  1.14255409e+00  1.00508032e+00  1.32397601e+00
   2.42325

array([[2, 2, 0],
       [1, 2, 1],
       [2, 1, 0],
       [0, 0, 2],
       [0, 2, 1],
       [0, 0, 2],
       [1, 1, 0],
       [1, 1, 1],
       [0, 0, 2],
       [2, 0, 0]])

In [9]:
from sklearn.datasets import make_multilabel_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.multioutput import ClassifierChain

X, Y = make_multilabel_classification(
   n_samples=12, n_classes=3, random_state=0
)

print(X, Y)

X_train, X_test, Y_train, Y_test = train_test_split(
   X, Y, random_state=0
)

base_lr = LogisticRegression(solver='lbfgs', random_state=0)

chain = ClassifierChain(base_lr, order='random', random_state=0)

result = chain.fit(X_train, Y_train).predict(X_test)
print(result)

chain.predict_proba(X_test)


[[3. 6. 1. 8. 0. 3. 3. 2. 3. 7. 0. 6. 3. 0. 0. 1. 5. 1. 5. 0.]
 [3. 5. 5. 2. 0. 3. 4. 1. 3. 7. 1. 4. 2. 0. 0. 3. 7. 1. 1. 1.]
 [3. 3. 5. 5. 3. 5. 4. 3. 4. 2. 2. 3. 3. 2. 1. 1. 3. 0. 2. 1.]
 [3. 6. 5. 4. 1. 5. 3. 0. 4. 1. 1. 4. 2. 2. 1. 2. 4. 1. 4. 3.]
 [1. 4. 4. 6. 0. 6. 1. 7. 2. 5. 0. 4. 1. 1. 2. 3. 4. 0. 3. 0.]
 [5. 4. 2. 9. 0. 5. 6. 3. 2. 1. 1. 4. 1. 0. 2. 1. 3. 2. 4. 3.]
 [4. 3. 3. 4. 3. 2. 1. 4. 2. 5. 5. 1. 5. 3. 4. 0. 4. 2. 8. 3.]
 [5. 3. 1. 0. 2. 3. 5. 0. 3. 1. 3. 6. 9. 1. 2. 2. 1. 1. 1. 0.]
 [2. 6. 4. 0. 2. 9. 4. 1. 3. 2. 2. 6. 1. 2. 0. 2. 0. 4. 3. 6.]
 [1. 2. 2. 2. 5. 4. 4. 2. 1. 1. 1. 4. 0. 3. 1. 3. 1. 3. 2. 2.]
 [3. 9. 4. 3. 0. 8. 2. 2. 5. 4. 1. 2. 3. 0. 2. 0. 4. 1. 1. 0.]
 [4. 5. 1. 1. 2. 1. 2. 3. 2. 1. 2. 5. 5. 5. 3. 5. 4. 0. 6. 3.]] [[0 1 0]
 [0 1 0]
 [1 1 1]
 [1 1 1]
 [0 1 0]
 [1 1 0]
 [0 0 0]
 [1 0 0]
 [0 0 1]
 [0 0 0]
 [0 1 0]
 [0 0 0]]
[[1. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


array([[0.83873122, 0.94314231, 0.4576149 ],
       [0.88781656, 0.3684047 , 0.26409868],
       [0.03213614, 0.99359669, 0.06257921]])