In [3]:
import numpy as np
from sklearn.utils.multiclass import type_of_target

y = np.array(['apple', 'pear', 'apple', 'orange'])
print(y)

print(type_of_target(y))


['apple' 'pear' 'apple' 'orange']
multiclass


In [2]:
import numpy as np
from sklearn.preprocessing import LabelBinarizer
y = np.array(['apple', 'pear', 'apple', 'orange'])
y_dense = LabelBinarizer().fit_transform(y)
print(y_dense)


from scipy import sparse
y_sparse = sparse.csr_matrix(y_dense)
print(y_sparse)

[[1 0 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]]
  (0, 0)	1
  (1, 2)	1
  (2, 0)	1
  (3, 1)	1


In [1]:
from sklearn import datasets
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC
X, y = datasets.load_iris(return_X_y=True)
OneVsRestClassifier(LinearSVC(random_state=0)).fit(X, y).predict(X)

C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [2]:
# logistic regression for multi-class classification using built-in one-vs-rest
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)
# define model
model = LogisticRegression(multi_class='ovr')
# fit model
model.fit(X, y)
# make predictions
yhat = model.predict(X)
print(yhat)

[1 0 1 2 0 2 1 2 0 1 1 0 2 1 0 1 2 0 1 0 0 1 0 2 0 0 2 0 1 1 2 1 0 2 0 0 0
 1 1 2 2 1 0 1 0 2 0 0 0 2 0 1 2 0 2 2 1 2 1 0 2 2 2 1 0 1 1 1 0 2 0 2 2 1
 0 0 0 0 0 1 2 0 2 0 2 2 2 1 0 1 2 1 1 1 0 2 0 2 1 1 0 1 1 0 0 0 2 2 2 2 1
 0 0 1 2 0 0 0 0 2 2 2 1 0 1 2 2 0 1 0 2 1 0 0 2 0 0 0 0 1 1 1 0 0 1 1 2 0
 0 1 1 1 2 1 0 0 2 2 1 0 2 1 2 2 1 0 2 0 2 1 0 0 0 0 0 1 2 0 2 1 0 1 0 0 1
 0 0 0 1 0 1 2 1 0 0 1 1 0 2 1 1 0 1 1 0 0 0 1 2 2 0 2 0 1 0 2 2 0 0 2 2 1
 2 2 1 0 1 1 2 1 1 1 1 2 1 1 1 1 2 0 2 2 2 2 0 0 0 1 2 2 2 0 2 2 2 2 1 2 0
 1 1 0 1 2 1 2 0 2 0 0 0 2 1 1 0 0 1 1 2 0 1 1 1 1 2 0 0 0 1 2 0 0 1 0 0 2
 0 0 2 1 2 0 2 2 0 2 0 2 1 1 2 2 1 2 0 1 2 2 2 0 0 0 1 2 1 0 2 1 0 1 2 0 0
 1 1 2 0 1 0 0 1 2 1 1 2 2 0 2 1 1 0 1 0 0 0 0 0 0 1 2 2 0 0 0 1 0 0 1 2 1
 0 2 1 0 1 0 1 1 1 0 1 0 2 0 1 1 0 1 1 1 1 0 0 0 1 2 2 2 0 0 0 1 1 1 1 0 2
 2 0 1 2 1 0 2 0 0 1 1 0 2 2 0 2 2 0 1 0 0 0 0 1 0 0 2 1 0 0 2 1 0 0 2 1 1
 2 0 0 2 0 1 0 0 0 2 0 0 0 1 0 1 0 1 0 0 0 1 0 0 1 2 1 2 0 0 2 1 2 0 0 1 2
 2 1 2 1 1 1 0 2 2 1 1 2 

In [4]:
# logistic regression for multi-class classification using a one-vs-rest
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)
# define model
model = LogisticRegression()
# define the ovr strategy
ovr = OneVsRestClassifier(model)
# fit model
ovr.fit(X, y)
# make predictions
yhat = ovr.predict(X)
print(yhat)

[1 0 1 2 0 2 1 2 0 1 1 0 2 1 0 1 2 0 1 0 0 1 0 2 0 0 2 0 1 1 2 1 0 2 0 0 0
 1 1 2 2 1 0 1 0 2 0 0 0 2 0 1 2 0 2 2 1 2 1 0 2 2 2 1 0 1 1 1 0 2 0 2 2 1
 0 0 0 0 0 1 2 0 2 0 2 2 2 1 0 1 2 1 1 1 0 2 0 2 1 1 0 1 1 0 0 0 2 2 2 2 1
 0 0 1 2 0 0 0 0 2 2 2 1 0 1 2 2 0 1 0 2 1 0 0 2 0 0 0 0 1 1 1 0 0 1 1 2 0
 0 1 1 1 2 1 0 0 2 2 1 0 2 1 2 2 1 0 2 0 2 1 0 0 0 0 0 1 2 0 2 1 0 1 0 0 1
 0 0 0 1 0 1 2 1 0 0 1 1 0 2 1 1 0 1 1 0 0 0 1 2 2 0 2 0 1 0 2 2 0 0 2 2 1
 2 2 1 0 1 1 2 1 1 1 1 2 1 1 1 1 2 0 2 2 2 2 0 0 0 1 2 2 2 0 2 2 2 2 1 2 0
 1 1 0 1 2 1 2 0 2 0 0 0 2 1 1 0 0 1 1 2 0 1 1 1 1 2 0 0 0 1 2 0 0 1 0 0 2
 0 0 2 1 2 0 2 2 0 2 0 2 1 1 2 2 1 2 0 1 2 2 2 0 0 0 1 2 1 0 2 1 0 1 2 0 0
 1 1 2 0 1 0 0 1 2 1 1 2 2 0 2 1 1 0 1 0 0 0 0 0 0 1 2 2 0 0 0 1 0 0 1 2 1
 0 2 1 0 1 0 1 1 1 0 1 0 2 0 1 1 0 1 1 1 1 0 0 0 1 2 2 2 0 0 0 1 1 1 1 0 2
 2 0 1 2 1 0 2 0 0 1 1 0 2 2 0 2 2 0 1 0 0 0 0 1 0 0 2 1 0 0 2 1 0 0 2 1 1
 2 0 0 2 0 1 0 0 0 2 0 0 0 1 0 1 0 1 0 0 0 1 0 0 1 2 1 2 0 0 2 1 2 0 0 1 2
 2 1 2 1 1 1 0 2 2 1 1 2 

In [6]:
# SVM for multi-class classification using built-in one-vs-one
from sklearn.datasets import make_classification
from sklearn.svm import SVC
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)
# define model
model = SVC(decision_function_shape='ovo')
# fit model
model.fit(X, y)
# make predictions
yhat = model.predict(X)
print(yhat)

[1 0 1 2 0 2 2 2 0 0 1 0 2 2 0 1 2 0 1 0 0 0 0 2 0 0 2 0 1 1 2 1 0 2 0 0 0
 1 2 2 2 1 0 0 1 1 0 0 1 1 0 1 2 1 1 2 2 2 1 0 2 2 2 1 0 1 1 0 0 0 2 1 1 0
 0 0 2 0 2 1 2 0 0 0 1 2 2 2 0 1 2 2 1 0 0 1 1 2 0 1 0 0 1 1 1 0 2 2 2 2 1
 2 0 2 2 0 0 0 0 1 2 2 1 2 2 2 2 0 1 0 2 1 0 0 2 2 0 0 0 1 1 0 0 2 0 1 2 0
 2 1 2 0 0 1 0 0 2 2 1 2 2 1 2 0 1 2 2 0 2 1 0 0 2 0 0 0 2 0 2 1 0 0 0 0 0
 0 0 0 1 0 1 2 1 0 0 1 1 0 0 1 1 1 2 1 0 0 2 1 2 2 1 2 0 0 0 2 2 2 0 2 2 1
 1 2 1 1 1 1 2 1 0 1 1 2 1 1 1 1 2 0 2 2 1 1 2 0 0 0 1 1 2 2 2 2 1 2 1 1 0
 1 1 1 1 2 1 2 0 2 0 0 0 2 1 1 0 0 1 2 2 0 1 0 0 1 1 1 1 2 1 2 0 2 1 0 0 1
 0 0 2 1 1 0 2 2 0 0 0 2 1 0 2 2 1 1 0 1 0 2 2 0 0 0 1 2 1 1 1 2 0 1 2 1 0
 1 1 2 0 1 0 0 1 2 0 1 2 2 2 2 0 1 0 1 0 0 2 0 0 0 1 2 1 0 0 0 1 0 0 1 0 1
 0 2 0 0 1 0 1 1 1 0 0 2 2 2 1 2 0 1 1 1 1 0 0 0 1 2 2 1 0 2 0 1 0 1 1 0 1
 2 0 0 2 1 0 2 0 0 1 2 0 2 2 0 2 2 2 0 0 2 2 2 1 0 0 1 1 0 2 2 1 0 0 2 2 1
 2 0 0 1 0 0 0 0 0 2 1 0 0 1 2 1 1 0 0 0 0 1 0 0 1 2 1 0 0 0 1 1 2 2 0 1 2
 2 0 2 2 0 1 0 2 2 1 1 2 

In [7]:
# SVM for multi-class classification using one-vs-one
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.multiclass import OneVsOneClassifier
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)
# define model
model = SVC()
# define ovo strategy
ovo = OneVsOneClassifier(model)
# fit model
ovo.fit(X, y)
# make predictions
yhat = ovo.predict(X)
print(yhat)

[1 0 1 2 0 2 2 2 0 0 1 0 2 2 0 1 2 0 1 0 0 0 0 2 0 0 2 0 1 1 2 1 0 2 0 0 0
 1 2 2 2 1 0 0 1 1 0 0 1 1 0 1 2 1 1 2 2 2 1 0 2 2 2 1 0 1 1 0 0 0 2 1 1 0
 0 0 2 0 2 1 2 0 0 0 1 2 2 2 0 1 2 2 1 0 0 1 1 2 0 1 0 0 1 1 1 0 2 2 2 2 1
 2 0 2 2 0 0 0 0 1 2 2 1 2 2 2 2 0 1 0 2 1 0 0 2 2 0 0 0 1 1 0 0 2 0 1 2 0
 2 1 2 0 0 1 0 0 2 2 1 2 2 1 2 0 1 2 2 0 2 1 0 0 2 0 0 0 2 0 2 1 0 0 0 0 0
 0 0 0 1 0 1 2 1 0 0 1 1 0 0 1 1 1 2 1 0 0 2 1 2 2 1 2 0 0 0 2 2 2 0 2 2 1
 1 2 1 1 1 1 2 1 0 1 1 2 1 1 1 1 2 0 2 2 1 1 2 0 0 0 1 1 2 2 2 2 1 2 1 1 0
 1 1 1 1 2 1 2 0 2 0 0 0 2 1 1 0 0 1 2 2 0 1 0 0 1 1 1 1 2 1 2 0 2 1 0 0 1
 0 0 2 1 1 0 2 2 0 1 0 2 1 0 2 2 1 1 0 1 0 2 2 0 0 0 1 2 1 1 1 2 0 1 2 1 0
 1 1 2 0 1 0 0 1 2 0 1 2 2 2 2 0 1 0 1 0 0 2 0 0 0 1 2 1 0 0 0 1 0 0 1 0 1
 0 2 0 0 1 0 1 1 1 0 0 2 2 2 1 2 0 1 1 1 1 0 0 0 1 2 2 1 0 2 0 1 0 1 1 0 1
 2 0 0 2 1 0 2 0 0 1 2 0 2 2 0 2 2 2 0 0 2 2 2 1 0 0 1 1 0 2 2 1 0 0 2 2 1
 2 2 0 1 0 0 0 0 0 2 1 0 0 1 2 1 1 0 0 0 0 1 0 0 1 2 1 1 0 0 1 1 2 2 0 1 2
 2 0 2 2 0 1 0 2 2 1 1 2 

In [8]:
from sklearn import datasets
from sklearn.multiclass import OneVsOneClassifier
from sklearn.svm import LinearSVC
X, y = datasets.load_iris(return_X_y=True)
OneVsOneClassifier(LinearSVC(random_state=0)).fit(X, y).predict(X)

C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
from sklearn import datasets
from sklearn.multiclass import OutputCodeClassifier
from sklearn.svm import LinearSVC
X, y = datasets.load_iris(return_X_y=True)
clf = OutputCodeClassifier(LinearSVC(random_state=0),
                           code_size=2, random_state=0)
clf.fit(X, y).predict(X)

C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
# multi-class classification dataset
from collections import Counter
from sklearn.datasets import make_classification
# define dataset
X, y = make_classification(n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=1, n_classes=3)
# summarize the dataset
print(X.shape, y.shape)
# summarize the number of classes
print(Counter(y))

(1000, 20) (1000,)
Counter({2: 335, 1: 333, 0: 332})


In [11]:
# evaluate error-correcting output codes for multi-class classification
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OutputCodeClassifier
# define dataset
X, y = make_classification(n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=1, n_classes=3)
# define the binary classification model
model = LogisticRegression()
# define the ecoc model
ecoc = OutputCodeClassifier(model, code_size=2, random_state=1)
# define the evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate the model and collect the scores
n_scores = cross_val_score(ecoc, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
# summarize the performance
print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Accuracy: 0.766 (0.037)


In [12]:
# use error-correcting output codes model as a final model and make a prediction
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OutputCodeClassifier
# define dataset
X, y = make_classification(n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=1, n_classes=3)
# define the binary classification model
model = LogisticRegression()
# define the ecoc model
ecoc = OutputCodeClassifier(model, code_size=2, random_state=1)
# fit the model on the whole dataset
ecoc.fit(X, y)
# make a single prediction
row = [[0.04339387, 2.75542632, -3.79522705, -0.71310994, -3.08888853, -1.2963487, -1.92065166, -3.15609907, 1.37532356, 3.61293237, 1.00353523, -3.77126962, 2.26638828, -10.22368666, -0.35137382, 1.84443763, 3.7040748, 2.50964286, 2.18839505, -2.31211692]]
yhat = ecoc.predict(row)
print('Predicted Class: %d' % yhat[0])

Predicted Class: 0


In [13]:
from sklearn import datasets
from sklearn.multiclass import OutputCodeClassifier
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

# 数据获取
iris = datasets.load_iris()
X, y = iris.data, iris.target
print("样本数量:%d, 特征数量:%d" % X.shape)

# 模型对象创建
# code_size: 指定最终使用多少个子模型，实际的子模型的数量=int(code_size*label_number)
# code_size设置为1，等价于ovr子模型个数；
# 设置为0~1, 那相当于使用比较少的数据划分，效果比ovr差; 
# 设置为大于1的值，那么相当于存在部分模型冗余的情况
clf = OutputCodeClassifier(LinearSVC(random_state=0), code_size=30, random_state=0)
# 模型构建
clf.fit(X, y)

# 输出预测结果值
print(clf.predict(X))
print("准确率:%.3f" % accuracy_score(y, clf.predict(X)))

# 模型属性输出
k = 1
for item in clf.estimators_:
    print("第%d个模型:" % k, end="")
    print(item)
    k += 1
print(clf.classes_)

样本数量:150, 特征数量:4


C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\efnxqng\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: Convergence

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1
 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
准确率:0.967
第1个模型:LinearSVC(random_state=0)
第2个模型:_ConstantPredictor()
第3个模型:LinearSVC(random_state=0)
第4个模型:LinearSVC(random_state=0)
第5个模型:LinearSVC(random_state=0)
第6个模型:LinearSVC(random_state=0)
第7个模型:LinearSVC(random_state=0)
第8个模型:LinearSVC(random_state=0)
第9个模型:_ConstantPredictor()
第10个模型:_ConstantPredictor()
第11个模型:LinearSVC(random_state=0)
第12个模型:LinearSVC(random_state=0)
第13个模型:LinearSVC(random_state=0)
第14个模型:_ConstantPredictor()
第15个模型:LinearSVC(random_state=0)
第16个模型:LinearSVC(random_state=0)
第17个模型:LinearSVC(random_state=0)
第18个模型:LinearSVC(random_state=0)
第19个模型:LinearSVC(random_state=0)
第20个模型:LinearSVC(random_state=0)
第21个模型:LinearSVC(random_state=0)
第22个模型:_ConstantPred