In [3]:
import numpy as np
from sklearn.utils.multiclass import type_of_target

y = np.array(['apple', 'pear', 'apple', 'orange'])
print(y)

print(type_of_target(y))


['apple' 'pear' 'apple' 'orange']
multiclass


In [2]:
import numpy as np
from sklearn.preprocessing import LabelBinarizer
y = np.array(['apple', 'pear', 'apple', 'orange'])
y_dense = LabelBinarizer().fit_transform(y)
print(y_dense)


from scipy import sparse
y_sparse = sparse.csr_matrix(y_dense)
print(y_sparse)

[[1 0 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]]
  (0, 0)	1
  (1, 2)	1
  (2, 0)	1
  (3, 1)	1
